### ISSUE TITLE
: Destination path "samples.git" already exists and is not an empty directory

### ISSUE THREAD

**Issue by tangoFoxtrott** [jyuch/gitbucket-backup-plugin#6]
Hey there,

I am running gitbucket in a docker container and try to use the backup plugin. I am receiving a lot of these:

`org.eclipse.jgit.api.errors.JGitInternalException: Destination path "samples.git" already exists and is not an empty directory
	at org.eclipse.jgit.api.CloneCommand.verifyDirectories(CloneCommand.java:246)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:166)
	at gitbucket.core.util.JGitUtil$.cloneRepository(JGitUtil.scala:874)
	at io.github.gitbucket.backup.actor.RepositoryCloneActor$$anonfun$receive$1.applyOrElse(RepositoryCloneActor.scala:21)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at io.github.gitbucket.backup.actor.RepositoryCloneActor.aroundReceive(RepositoryCloneActor.scala:11)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

This is my Configuration

```
akka {
  quartz {
    schedules {
      Backup {
         expression = "* 0/5 * * * ?"
      }
    }
  }
}

backup {
  # Backup archive destination directory (Optional)
  # If not specified, archive is saved into GITBUCKET_HOME
  archive-destination = "/backup"

  # Maximum number of backup archives to keep (if 0 or negative value, keep unlimited) (Optional)
  # If not specified, keep unlimited
  archive-limit = 10

  # Send notify email when backup is success (Optional, default:false)
  notify-on-success = false

  # Send notify email when backup is failure (Optional, default:false)
  notify-on-failure = true

  # Notify email destination (Optional)
  notify-dest = ["xxx@yyy"]

  # S3 compatible object storage for backup upload (Optional)
  s3 {
    # Endpoing URL
    endpoint = "http://xxx:9000"

    # Region
    region = "US_EAST_1"

    # Access key
    access-key = "secret"

    # Secret key
    secret-key = "secret"

    # Bucket of backup destination
    bucket = "gitbucket"
  }
}
```
I am using gitbucket 4.34.0 and backup-plugin 1.2.3.

Any hint on what I am doing wrong?

**Comment by tangoFoxtrott** [comment]
So it turned out, that if you use:

"* 0/5 * * * ?"

as scheduler pattern, it tries to do 60 Backups every 5 minutes which will lead to interessting file locking issues. Changed the pattern to something useful and it works like a charm.
