### ISSUE TITLE
Plugin not respond to archive-destination

### ISSUE THREAD

**Issue by LowDensity** [jyuch/gitbucket-backup-plugin#7]
The plugin doesnt seem to recognize the archive-destination set in the backup.conf file.

I tried the following variant and non of them worked.
archive-destination =/folder1
archive-destination =E:\
archive-destination =E:/
archive-destination ="""folder1"""
archive-destination ="folder1"
archive-destination ="E"
archive-destination ="E:\"
  
It either returns HTTP 500 (when execute through POST request) or simply put things into GITBUCKET_HOME(when executed on schedule) and completely ignore archive-destination.

**Comment by jyuch** [comment]
You have to specify `archive-destination` in full path.
e.g. `archive-destination ="""E:\foo\bar"""`

Can you provide content of  `backup.conf` and log file ?
(mask sensitive information if needed.)

**Comment by LowDensity** [comment]
I had my configuration changed to 
`archive-destination="""E:\"""`
I have designated the Entire E drive as backup storage and intended to place backup file 
in root of drive E.
It still puts backup file into  GITBUCKET_HOME after setting.

Here's my current backup.conf 
[backup.txt](https://github.com/jyuch/gitbucket-backup-plugin/files/5572183/backup.txt)

**Comment by jyuch** [comment]
I was unable to reproduce this issue using your configuration file.

Can you provide little more information ?

- GitBucket deployment mode (standalone app, under webcontainer)
- JRE vendor and version
- Other installed plugins
- Log file

Could it be that the E-drive is a network drive and running GitBucket as a service?
If so, then maybe the backup plugin is not able to access the E drive.
(Network drive is connected by Explorer at login.)

**Comment by LowDensity** [comment]
>> GitBucket deployment mode (standalone app, under webcontainer)
>> JRE vendor and version
GitBucket was deployed in following environment:

- Windows Server 2019 Standard
- apache-tomee-plume-7.1.1(set as a service)
- Oracle JDK 11.0.5

>>Other installed plugins
- gist:4.18.0
- emoji:4.6.0
- pages:1.8.0
- notifications:1.8.0

>>Log file

> [ERROR] [11/20/2020 16:25:46.080] [backup-akka.actor.default-dispatcher-10] [akka://backup/user/backup/packer] java.io.FileNotFoundException: E:\backup-202011201624.zip (Access is denied)
org.zeroturnaround.zip.ZipException: java.io.FileNotFoundException: E:\backup-202011201624.zip (Access is denied)
	at org.zeroturnaround.zip.ZipExceptionUtil.rethrow(ZipExceptionUtil.java:11)
	at org.zeroturnaround.zip.ZipUtil.pack(ZipUtil.java:1631)
	at org.zeroturnaround.zip.ZipUtil.pack(ZipUtil.java:1419)
	at org.zeroturnaround.zip.ZipUtil.pack(ZipUtil.java:1402)
	at io.github.gitbucket.backup.actor.FinishingActor$$anonfun$receive$1.applyOrElse(FinishingActor.scala:41)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at io.github.gitbucket.backup.actor.FinishingActor.aroundReceive(FinishingActor.scala:22)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.FileNotFoundException: E:\backup-202011201624.zip (Access is denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at org.zeroturnaround.zip.ZipUtil.pack(ZipUtil.java:1626)
	... 15 more

Thanks for the guidance , I finally found the logs.
Looks like a permission denied. 
I just updated the permission of user "Local Service". 
Specifying write permission of E:\ to this user.
I am going to do some more check tomorrow.
I will raise another issue if it there's still problem. Thanks a lot.
