### ISSUE TITLE
Error during starting gitbucket with backup plugin

### ISSUE THREAD

**Issue by lilian-benoit** [jyuch/gitbucket-backup-plugin#9]
**Environment :**

    Gitbucket standalone 4.35.3 ou 4.36.0
    AdoptOpenJDK : 11.0.11
    List of installed plugins : default only.
    OS : Linux

**Error during starting gitbucket**
```
 [INFO] [07/17/2021 23:34:51.582] [main] [[QuartzScheduler~backup]] Initialized calendars: 
Uncaught error from thread [backup-akka.actor.default-dispatcher-2]: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[backup]
java.lang.NoClassDefFoundError: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException(FaultHandling.scala:310)
	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException$(FaultHandling.scala:310)
	at akka.actor.ActorCell.handleNonFatalOrInterruptedException(ActorCell.scala:447)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:557)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

```

**Comment by jyuch** [comment]
I was unable to reproduce the problem those environment.
Can you provide little more information ?

- Ubuntu 20.04.2 LTS (Focal Fossa)
- Amazon Corretto 11
- GitBucket 4.36.2 and 4.35.3
- gitbucket-backup-plugin 1.2.3

And GitBucket requires Java8, so you might want to run GitBucket using Java8.
